package org.example.view;

import javax.swing.*;
import javax.swing.text.html.HTMLEditorKit;
import java.awt.*;

// Plain-language guide to the street-network data shown in the app.
public class MetricGuidePanel extends JPanel {
    public MetricGuidePanel() {
        setLayout(new BorderLayout());
        setBackground(Color.WHITE);
        JEditorPane pane = new JEditorPane();
        pane.setEditorKit(new HTMLEditorKit());
        pane.setEditable(false);
        pane.setBackground(Color.WHITE);
        pane.setText(buildHtml());
        JScrollPane scroll = new JScrollPane(pane);
        scroll.getVerticalScrollBar().setUnitIncrement(16);
        scroll.setBorder(BorderFactory.createEmptyBorder());
        add(scroll, BorderLayout.CENTER);
        SwingUtilities.invokeLater(() -> pane.setCaretPosition(0));
    }
    private static String buildHtml() {
        return "<html><head><style>"
                + "body  { font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px; "
                + "        color: #212529; margin: 24px 36px; line-height: 1.7; }"
                + "h1    { color: #1565C0; font-size: 20px; border-bottom: 2px solid #1565C0; "
                + "        padding-bottom: 6px; }"
                + "h2    { color: #1976D2; font-size: 16px; margin-top: 26px; "
                + "        border-left: 4px solid #1976D2; padding-left: 8px; }"
                + "h3    { color: #0D47A1; font-size: 14px; margin-top: 16px; }"
                + ".card { background: #F5F9FF; border: 1px solid #BBDEFB; "
                + "        border-radius: 6px; padding: 12px 16px; margin: 10px 0; }"
                + ".tip   { background: #E8F5E9; border-left: 3px solid #2E7D32; "
                + "         padding: 8px 12px; margin: 10px 0; }"
                + "table { border-collapse: collapse; width: 100%; margin: 12px 0; }"
                + "th    { background: #1565C0; color: white; padding: 8px 10px; text-align: left; }"
                + "td    { border: 1px solid #BBDEFB; padding: 7px 10px; vertical-align: top; }"
                + "tr:nth-child(even) td { background: #F5F9FF; }"
                + "</style></head><body>"

                + "<h1>Understanding the Data</h1>"
                + "<div class='card'>"
                + "This app reads <b>street maps</b> from OpenStreetMap (OSM), the free, "
                + "community-built map of the world. Each city is stored as a <b>GraphML file</b>: "
                + "a list of <b>junctions</b> (nodes) connected by <b>road segments</b> (edges), "
                + "with tags describing each street (type, speed limit, lanes, and so on)."
                + "</div>"
                + "<p>"
                + "You do not need a background in mathematics to use the Dashboard, Map, or Charts. "
                + "Those tabs focus on everyday questions: <i>How long are the roads? How walkable is "
                + "the city? How many one-way streets are there?</i>"
                + "</p>"

                + "<h2>Where the numbers come from</h2>"
                + "<p>"
                + "When you load a GraphML file, the app extracts two kinds of information:"
                + "</p>"
                + "<table>"
                + "<tr><th>Kind of data</th><th>What it tells you</th><th>Where you see it</th></tr>"
                + "<tr><td><b>Street tags (OSM)</b></td>"
                + "<td>Real-world road properties: type, length, speed, lanes, names, bridges…</td>"
                + "<td>Dashboard, Map, Charts</td></tr>"
                + "<tr><td><b>Network structure</b></td>"
                + "<td>How junctions connect - used for advanced analysis (optional)</td>"
                + "<td>Analysis tab, Results tab, some Charts</td></tr>"
                + "</table>"
                + "<div class='tip'>"
                + "<b>Good to know:</b> Street statistics come directly from map tags. "
                + "They are the same whether you choose Quick or Full analysis. "
                + "Quick vs Full only affects how long the app spends on deeper network calculations."
                + "</div>"

                + "<h2>Dashboard: your city at a glance</h2>"
                + "<p>The summary cards and table answer simple comparison questions:</p>"
                + "<table>"
                + "<tr><th>What you see</th><th>In plain English</th></tr>"
                + "<tr><td><b>Total road length</b></td>"
                + "<td>How many kilometres of streets are in the map.</td></tr>"
                + "<tr><td><b>One-way streets</b></td>"
                + "<td>What share of segments only allow traffic in one direction.</td></tr>"
                + "<tr><td><b>Speed limit</b></td>"
                + "<td>Average posted speed where OSM has a <i>maxspeed</i> tag (not every road is tagged).</td></tr>"
                + "<tr><td><b>Residential / car-oriented</b></td>"
                + "<td>How much of the network is local neighbourhood streets vs main roads and motorways.</td></tr>"
                + "<tr><td><b>Walkable / cycling</b></td>"
                + "<td>Share of length on footpaths, pedestrian zones, cycleways, and similar.</td></tr>"
                + "<tr><td><b>Named roads</b></td>"
                + "<td>How many segments have a street name in the map data.</td></tr>"
                + "<tr><td><b>Bridges &amp; tunnels</b></td>"
                + "<td>Count of segments marked as crossing water or running underground.</td></tr>"
                + "<tr><td><b>Streets per junction</b></td>"
                + "<td>On average, how many roads meet at each intersection - higher often means a denser grid.</td></tr>"
                + "<tr><td><b>Dominant street type</b></td>"
                + "<td>The most common OSM <i>highway</i> category in that city (usually <i>residential</i>).</td></tr>"
                + "</table>"

                + "<h2>OSM street tags we use</h2>"
                + "<p>"
                + "OpenStreetMap volunteers tag each road with labels. The app reads these from your GraphML files:"
                + "</p>"
                + "<table>"
                + "<tr><th>Tag</th><th>What it means</th></tr>"
                + "<tr><td><b>highway</b></td>"
                + "<td>Road category - e.g. residential, primary, footway, cycleway, living_street.</td></tr>"
                + "<tr><td><b>length</b></td>"
                + "<td>Segment length in metres (used for km totals and percentage breakdowns).</td></tr>"
                + "<tr><td><b>maxspeed</b></td>"
                + "<td>Speed limit in km/h where recorded.</td></tr>"
                + "<tr><td><b>lanes</b></td>"
                + "<td>Number of traffic lanes where recorded.</td></tr>"
                + "<tr><td><b>oneway</b></td>"
                + "<td>Whether traffic is allowed in only one direction.</td></tr>"
                + "<tr><td><b>name</b></td>"
                + "<td>Street name - used to calculate how many roads are named.</td></tr>"
                + "<tr><td><b>bridge / tunnel</b></td>"
                + "<td>Marks infrastructure that goes over or under something else.</td></tr>"
                + "<tr><td><b>width / est_width</b></td>"
                + "<td>Physical or estimated road width in metres (when tagged).</td></tr>"
                + "<tr><td><b>access</b></td>"
                + "<td>Whether general traffic is allowed (private, restricted, etc.).</td></tr>"
                + "</table>"

                + "<h3>Common highway types</h3>"
                + "<p>These appear in charts and on the map colour legend:</p>"
                + "<ul>"
                + "<li><b>residential</b> - neighbourhood streets, usually slower and local.</li>"
                + "<li><b>primary / secondary / tertiary</b> - increasingly important through-roads.</li>"
                + "<li><b>motorway / trunk</b> - fast, high-capacity roads (often car-oriented).</li>"
                + "<li><b>living_street</b> - shared space where pedestrians have priority.</li>"
                + "<li><b>footway / pedestrian / steps</b> - walking infrastructure.</li>"
                + "<li><b>cycleway</b> - dedicated or preferred cycling routes.</li>"
                + "<li><b>service / unclassified</b> - access roads, alleys, or minor links.</li>"
                + "</ul>"

                + "<h2>Other tabs: what they are for</h2>"

                + "<h3>Map</h3>"
                + "<p>"
                + "An interactive drawing of the street network. You can colour roads by "
                + "<b>type</b>, <b>speed limit</b>, <b>one-way vs two-way</b>, or "
                + "<b>bridges &amp; tunnels</b>. Hover over a segment to see its OSM tags."
                + "</p>"

                + "<h3>Charts</h3>"
                + "<p>"
                + "Bar charts comparing cities side by side: road length, street types, walking and "
                + "cycling share, speed limits, and more. Street-related charts are listed first; "
                + "deeper network charts appear further down."
                + "</p>"

                + "<h3>Analysis</h3>"
                + "<p>"
                + "A <b>full written report</b>: press Generate Report after processing. "
                + "It includes street statistics, graph metrics, rankings, and research context "
                + "in one scrollable document."
                + "</p>"

                + "<h3>Full metrics table (section 7 of the report)</h3>"
                + "<p>"
                + "Near the end of the Analysis report you will find a compact table, one row per city, "
                + "sorted by <b>node count</b> (largest networks first). The same graph metrics appear "
                + "in the <b>Results</b> tab with fuller column names. Below is what each abbreviated "
                + "column means."
                + "</p>"
                + "<table>"
                + "<tr><th>Column</th><th>What it measures</th><th>How to read it</th></tr>"
                + "<tr><td><b>Network</b></td>"
                + "<td>City label taken from the GraphML filename.</td>"
                + "<td>Underscores stand in for spaces; the comma separates city and country "
                + "(e.g. <i>Bangkok,_Thailand</i>).</td></tr>"
                + "<tr><td><b>Nodes</b></td>"
                + "<td>Number of junctions in the map.</td>"
                + "<td>More nodes usually means a larger extracted street network, not necessarily a "
                + "bigger real-world city.</td></tr>"
                + "<tr><td><b>Edges</b></td>"
                + "<td>Number of street segments connecting junctions.</td>"
                + "<td>Counts every link in the graph; one-way pairs may count differently depending on "
                + "how the file was built.</td></tr>"
                + "<tr><td><b>Betw.</b></td>"
                + "<td><b>Betweenness centrality</b> (average): how often a junction sits on shortest "
                + "routes between others.</td>"
                + "<td>Higher values point to more critical connectors or bottlenecks. "
                + "<b>N/A</b> means Quick analysis skipped this on a very large network.</td></tr>"
                + "<tr><td><b>Clos.</b></td>"
                + "<td><b>Closeness centrality</b> (average): how near a typical junction is to all "
                + "others, in hop count.</td>"
                + "<td>Values are scaled for comparison across cities. In the reference research, "
                + "lower closeness is discussed alongside mobility outcomes. <b>N/A</b> if not computed.</td></tr>"
                + "<tr><td><b>Deg.</b></td>"
                + "<td><b>Degree centrality</b> (average): how many connections a typical junction has.</td>"
                + "<td>Higher means busier intersections on average. Small decimals are normal on "
                + "large networks.</td></tr>"
                + "<tr><td><b>Clust.</b></td>"
                + "<td><b>Clustering coefficient</b>: how often neighbouring junctions link to each other.</td>"
                + "<td>Higher values mean tighter local grids or triangles. This metric is strongly "
                + "linked to UMRi in the 62-city reference study. <b>N/A</b> if not computed.</td></tr>"
                + "<tr><td><b>Diam</b></td>"
                + "<td><b>Graph diameter</b>: the longest shortest path across the network, in hops.</td>"
                + "<td>Smaller diameter usually means a more compact city on the map. "
                + "<b>N/A</b> if path sampling could not estimate it.</td></tr>"
                + "<tr><td><b>Density</b></td>"
                + "<td>Share of possible connections that actually exist.</td>"
                + "<td>Higher density means a denser mesh of streets relative to the number of "
                + "junctions. Very small numbers are expected on large urban graphs.</td></tr>"
                + "<tr><td><b>AvgPath</b></td>"
                + "<td><b>Average path length</b>: mean number of hops between pairs of junctions.</td>"
                + "<td>Lower values mean shorter typical cross-city trips on the network. "
                + "Useful for comparing connectivity shape, not real travel time.</td></tr>"
                + "</table>"
                + "<div class='tip'>"
                + "<b>Comparing cities fairly:</b> Raw node and edge counts reflect map size and "
                + "extraction detail. For mobility structure, focus on clustering, diameter, density, "
                + "and average path length. The Results tab labels some columns with "
                + "<i>(high)</i> or <i>(low)</i> to show the direction tied to better UMRi scores in "
                + "the Sierra-Porta &amp; Herrera-Acevedo (2024) study, not a universal rule for every city."
                + "</div>"
                + "<div class='card'>"
                + "<b>Why do I see N/A?</b> In <b>Quick</b> mode the app may skip or sample the slowest "
                + "calculations on very large networks (for example Bangkok). Switch to <b>Full</b> "
                + "analysis and re-process if you need every cell filled in."
                + "</div>"

                + "<h3>Quick vs Full analysis</h3>"
                + "<div class='card'>"
                + "<b>Quick</b> (default): fast. On very large cities it estimates some deep network "
                + "numbers and may skip the slowest calculations.<br><br>"
                + "<b>Full</b>: exact network maths on every junction. Can take hours on huge cities. "
                + "Use this only if you specifically need precise structural metrics for research."
                + "</div>"
                + "<p>"
                + "For most users comparing street types, speeds, and walkability, <b>Quick is enough</b>."
                + "</p>"

                + "<h3>Results table</h3>"
                + "<p>"
                + "A sortable spreadsheet of every number computed for each city: street stats "
                + "and network metrics together. Useful for exporting or digging into specifics. "
                + "See <b>Full metrics table</b> above for plain-English definitions of the graph "
                + "columns (Betweenness, Closeness, Diameter, and so on)."
                + "</p>"

                + "<h2>Things to keep in mind</h2>"
                + "<ul>"
                + "<li><b>Map quality varies.</b> OSM is volunteer-maintained; some cities are richly "
                + "tagged, others have gaps (missing speed limits, lane counts, or names).</li>"
                + "<li><b>Percentages are length-weighted.</b> A 10% footway share means 10% of total "
                + "road <i>length</i>, not 10% of individual streets.</li>"
                + "<li><b>GraphML files are snapshots.</b> They reflect the map at the time the file "
                + "was created, not live traffic or road works today.</li>"
                + "</ul>"

                + "<br><hr>"
                + "<p style='color:#888; font-size:11px;'>"
                + "Street data originates from "
                + "<a href='https://www.openstreetmap.org/copyright'>OpenStreetMap contributors</a>. "
                + "Network files are typically built with tools such as OSMnx."
                + "</p>"
                + "</body></html>";
    }
}